"""
data/synthetic/generate_production_data.py

Generates SYNTHETIC training data for Model 2 (Production Prediction Model).

*** THIS DATA IS 100% SYNTHETIC. IT IS NOT REAL BAGHEWALA FIELD DATA. ***

Strategy (per specification's "Data source strategy" for Model 2):
    "Physics-simulated production trajectories generated by chaining Model 1
    output through a simplified inflow-performance relationship."

Pipeline:
    1. Reuse the SAME well-cycle parameter sampling style as Model 1's
       generator, so units/ranges are consistent across the project.
    2. For each well-cycle, call Model 1's PHYSICS BACKBONE directly (not
       the trained Stage-B model, to avoid a chicken-and-egg dependency
       during data generation -- physics-only is enough to get a
       plausible temperature/viscosity trajectory for synthetic BOPD
       generation) to get a viscosity trajectory across the production
       phase.
    3. Sample SRP operating settings (SPM, stroke length, VFD frequency)
       and water cut per well-cycle.
    4. Compute production via simplified_ipr_bopd() (pump/reservoir
       potential) modulated by an Arps decline shape over day-count within
       the cycle (near-wellbore drainage depletion), then add noise.
    5. Save to production_data.csv with `temperature_C` / `viscosity_cP`
       columns using the SAME NAMES as Model 1's outputs, per the
       requirement that "Model 2 must accept exactly those concepts rather
       than inventing another variable name."

Run:
    cd Baghewala_Digital_Twin
    python data/synthetic/generate_production_data.py

Output:
    data/synthetic/production_data.csv
"""

import os
import sys
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from physics.thermal_physics import (
    ThermalPhysicsParams,
    temperature_trajectory,
    temperature_to_viscosity_cP,
)
from physics.production_physics import simplified_ipr_bopd, arps_decline_bopd

RNG_SEED = 43
N_WELL_CYCLES = 200
DAYS_PER_CYCLE_PRODUCTION = 40   # days of production phase sampled per cycle
SAMPLES_PER_CYCLE = 20
OUT_PATH = os.path.join(os.path.dirname(__file__), "production_data.csv")


def generate():
    rng = np.random.default_rng(RNG_SEED)
    phys_params = ThermalPhysicsParams()
    rows = []

    well_id = 0
    for wc in range(N_WELL_CYCLES):
        if wc % rng.integers(2, 4) == 0:
            well_id += 1
        cycle_num = int(rng.integers(1, 6))

        # --- reservoir/CSS params (same ranges as Model 1 generator) ---
        steam_volume_bbl = rng.uniform(600, 2200)
        injection_pressure_psi = rng.uniform(150, 450)
        steam_quality_frac = rng.uniform(0.55, 0.85)
        soak_duration_days = rng.uniform(4, 12)
        thermal_conductivity = rng.uniform(1.3, 2.4)
        porosity = rng.uniform(0.20, 0.32)
        thickness = rng.uniform(6, 20)
        baseline_temp = rng.uniform(46, 48)
        api_gravity = rng.uniform(17, 19)
        prior_cycle_count = cycle_num - 1

        # --- SRP operating settings for this well-cycle (fairly stable
        #     across the cycle, as operators don't change SPM/stroke daily) ---
        spm = rng.uniform(3, 7)
        stroke_length_in = rng.uniform(64, 144)
        vfd_hz = rng.uniform(35, 60)
        water_cut = np.clip(rng.normal(0.15, 0.08), 0.0, 0.6)

        # --- Arps decline shape parameters for this cycle ---
        arps_di = rng.uniform(0.015, 0.05)
        arps_b = rng.uniform(0.2, 0.55)

        day_counts = np.sort(rng.uniform(0, DAYS_PER_CYCLE_PRODUCTION, SAMPLES_PER_CYCLE))
        t_since_injection = soak_duration_days + day_counts  # production phase only

        cum_prod_guess = day_counts * 40  # rough guess just to drive Model1 backbone's
                                            # production-phase extra-decay term
        temps = temperature_trajectory(
            t_days=t_since_injection,
            phase_days={"soak": soak_duration_days},
            baseline_temp_C=baseline_temp,
            steam_volume_bbl=steam_volume_bbl,
            injection_pressure_psi=injection_pressure_psi,
            steam_quality_frac=steam_quality_frac,
            soak_duration_days=soak_duration_days,
            thermal_conductivity_W_mK=thermal_conductivity,
            porosity_frac=porosity,
            formation_thickness_m=thickness,
            prior_cycle_count=prior_cycle_count,
            cum_production_bbl_series=cum_prod_guess,
            params=phys_params,
        )
        viscosities = temperature_to_viscosity_cP(temps)

        # potential rate from IPR/pump-capacity at each viscosity
        potential = np.array([
            simplified_ipr_bopd(v, spm, stroke_length_in, vfd_hz, water_cut)
            for v in viscosities
        ])
        # Arps decline envelope (normalized to 1.0 at day 0) modulates the
        # potential rate to represent near-wellbore drainage depletion over
        # the cycle, on top of the viscosity effect already in `potential`.
        decline_envelope = arps_decline_bopd(qi_bopd=1.0, di_per_day=arps_di, b=arps_b, t_days=day_counts)

        true_bopd = potential * decline_envelope
        noise = rng.normal(0, 0.06 * (true_bopd + 5))  # heteroscedastic-ish noise
        observed_bopd = np.clip(true_bopd + noise, 0, None)

        cum_prod_running = np.cumsum(observed_bopd * np.diff(np.concatenate([[0], day_counts])))
        lagged_bopd = np.concatenate([[observed_bopd[0]], observed_bopd[:-1]])

        for i in range(SAMPLES_PER_CYCLE):
            phase = "production"
            rows.append({
                "well_id": f"BGW-{well_id:03d}",
                "cycle_num": cycle_num,
                "day_count_in_cycle": round(float(day_counts[i]), 2),
                "phase": phase,
                "temperature_C": round(float(temps[i]), 3),
                "viscosity_cP": round(float(viscosities[i]), 2),
                "spm": round(float(spm), 2),
                "stroke_length_in": round(float(stroke_length_in), 1),
                "vfd_frequency_hz": round(float(vfd_hz), 1),
                "water_cut_frac": round(float(water_cut), 3),
                "cum_production_this_cycle_bbl": round(float(cum_prod_running[i]), 1),
                "lagged_bopd": round(float(lagged_bopd[i]), 2),
                "bopd": round(float(observed_bopd[i]), 2),
                "is_synthetic": True,
                "data_source": "physics_chained_synthetic",
            })

    df = pd.DataFrame(rows)
    df.to_csv(OUT_PATH, index=False)
    print(f"Wrote {len(df)} rows ({df['well_id'].nunique()} wells) to {OUT_PATH}")
    print(df.head(8).to_string())
    return df


if __name__ == "__main__":
    generate()
