"""
physics/production_physics.py

Lightweight physics/engineering helper functions used by Model 2
(Production Prediction Model):

  1. simplified_ipr_bopd(...)   - a simplified Inflow Performance Relationship
     used ONLY to generate physically-reasonable SYNTHETIC production data
     (per spec: "Physics-simulated production trajectories generated by
     chaining Model 1 output through a simplified inflow-performance
     relationship").

  2. arps_decline_bopd(...)     - classic Arps hyperbolic decline-curve
     equation. Used for TWO purposes:
       a) as part of the synthetic data generator (imposes decline shape)
       b) as the "soft physics-consistency regularizer" referenced in the
          spec: an auxiliary engineered feature + post-hoc diagnostic that
          nudges Model 2's XGBoost predictions towards decline-curve-
          consistent shapes, WITHOUT hard-constraining them (since real
          production is also driven by things Arps curves don't capture:
          skin damage, sanding, interventions, etc. -- exactly as the spec
          warns against forcing an unrealistic physics constraint).

PROTOTYPE APPROXIMATION NOTICE: none of the constants here are fit to real
Baghewala production history (we don't have it yet). They are chosen to be
directionally and order-of-magnitude reasonable for a heavy-oil CSS well
producing at up to a few hundred BOPD, per typical CSS heavy-oil field
analogs referenced in the specification document.
"""

from __future__ import annotations
from dataclasses import dataclass
import numpy as np


@dataclass
class IPRParams:
    # Productivity-style constant translating (1/viscosity) into a flow
    # potential. Prototype-tuned so that at ~50 cP viscosity and full pump
    # capacity, potential rate is in the low hundreds of BOPD range.
    productivity_constant: float = 9500.0

    # Pump volumetric capacity constant (BOPD per unit of SPM*stroke_in*VFD_ratio)
    pump_capacity_constant: float = 0.85

    # Reference VFD frequency (Hz) representing "1.0x" pump speed ratio
    reference_vfd_hz: float = 50.0

    # How strongly high viscosity degrades pump volumetric efficiency
    # (heavy oil -> more slippage / gas-free fluid pound effects, prototype)
    viscosity_efficiency_loss: float = 0.35
    reference_viscosity_cP_for_efficiency: float = 200.0


def simplified_ipr_bopd(
    viscosity_cP: float,
    spm: float,
    stroke_length_in: float,
    vfd_frequency_hz: float,
    water_cut_frac: float = 0.0,
    params: IPRParams = IPRParams(),
) -> float:
    """
    Simplified inflow-performance + pump-capacity-limited production rate
    (gross-to-oil, after water-cut split), in BOPD.

    q_potential  ~ productivity_constant / viscosity      (reservoir supply)
    q_pump_cap   ~ pump_capacity_constant * SPM * stroke * (VFD/ref)
                   * (efficiency de-rate for viscosity)   (pump-lift limit)
    q_actual     = min(q_potential, q_pump_cap) * (1 - water_cut)

    PROTOTYPE APPROXIMATION: real IPR relationships are typically far more
    involved (Vogel/Fetkovich curves, multiphase flow, skin factors). This
    linear-in-(1/viscosity) form is a deliberately simple prototype stand-in,
    clearly documented as such.
    """
    viscosity_cP = max(viscosity_cP, 1.0)
    q_potential = params.productivity_constant / viscosity_cP

    vfd_ratio = vfd_frequency_hz / params.reference_vfd_hz
    efficiency = 1.0 / (
        1.0
        + params.viscosity_efficiency_loss
        * (viscosity_cP / params.reference_viscosity_cP_for_efficiency)
    )
    q_pump_cap = params.pump_capacity_constant * spm * stroke_length_in * vfd_ratio * efficiency

    q_gross = min(q_potential, q_pump_cap)
    q_oil = q_gross * (1.0 - np.clip(water_cut_frac, 0.0, 0.95))
    return max(q_oil, 0.0)


def arps_decline_bopd(qi_bopd: float, di_per_day: float, b: float, t_days) -> np.ndarray:
    """
    Arps decline-curve equation.

        b == 0            : exponential decline   q = qi * exp(-Di*t)
        0 < b < 1 (typical): hyperbolic decline    q = qi / (1 + b*Di*t)^(1/b)
        b == 1             : harmonic decline      q = qi / (1 + Di*t)

    Parameters
    ----------
    qi_bopd : initial (peak, start-of-cycle) rate, BOPD
    di_per_day : initial nominal decline rate (1/day)
    b : Arps hyperbolic exponent, typically 0.1-0.6 for heavy-oil CSS cycles
    t_days : array-like, days since cycle production start (t=0 -> qi)
    """
    t = np.atleast_1d(np.asarray(t_days, dtype=float))
    t = np.clip(t, 0, None)
    if abs(b) < 1e-6:
        q = qi_bopd * np.exp(-di_per_day * t)
    elif abs(b - 1.0) < 1e-6:
        q = qi_bopd / (1.0 + di_per_day * t)
    else:
        q = qi_bopd / np.power(1.0 + b * di_per_day * t, 1.0 / b)
    return np.clip(q, 0.0, None)


if __name__ == "__main__":
    q = simplified_ipr_bopd(viscosity_cP=80, spm=5, stroke_length_in=86, vfd_frequency_hz=50)
    print(f"IPR/pump-limited rate at 80 cP: {q:.1f} BOPD")

    t = np.arange(0, 30, 5)
    decline = arps_decline_bopd(qi_bopd=150, di_per_day=0.03, b=0.35, t_days=t)
    for ti, qi in zip(t, decline):
        print(f"t={ti:3d}d  q={qi:6.1f} BOPD")
